image: Visual Studio 2017
platform: Any CPU

environment:
  version: $(APPVEYOR_BUILD_VERSION)

configuration:
- Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%version%'
  package_version: '%version%'
  assembly_version: '%version%'
  file_version: '%version%'
  informational_version: '%version%'

before_build:
  - dotnet restore

build:
  project: Mundipagg.NetStandard.sln

after_test:
  - dotnet pack --configuration Release /p:Version=%version%

artifacts:
  - path: Mundipagg.NetStandard\bin\Release\netstandard2.0\Mundipagg.NetStandard.dll
    name: Mundipagg.NetStandard.dll
  - path: Mundipagg.NetStandard\bin\Release\Mundipagg.NetStandard.%version%.nupkg
    name: Mundipagg.NetStandard.%version%.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: hb5jOmzsvUKCtOP41EFtc/lwXAOh5auC5KAi2Ok9i/FmTuo2F36yzEgaPiT9olsB